
  def responses(id)

    resp = {}
    resp[100] = "Continue"
    resp[101] = "Switching Protocols"
    resp[102] = "Processing"

    resp[200] = "OK"
    resp[201] = "Created"
    resp[202] = "Accepted"
    resp[203] = "Non-authoritative Information"
    resp[204] = "No Content"
    resp[205] = "Reset Content"
    resp[206] = "Partial Content"
    resp[207] = "Multi-Status"
    resp[208] = "Already Reported"
    resp[226] = "IM Used"

    resp[300] = "Multiple Choices"
    resp[301] = "Moved Permanently"
    resp[302] = "Found"
    resp[303] = "See Other"
    resp[304] = "Not Modified"
    resp[305] = "Use Proxy"
    resp[307] = "Temporary Redirect"
    resp[308] = "Permanent Redirect"

    resp[400] = "Bad Request"
    resp[401] = "Unauthorized"
    resp[402] = "Payment Required"
    resp[403] = "Forbidden"
    resp[404] = "Not Found"
    resp[405] = "Method Not Allowed"
    resp[406] = "Not Acceptable"
    resp[407] = "Proxy Authentication Required"
    resp[408] = "Request Timeout"
    resp[409] = "Conflict"
    resp[410] = "Gone"
    resp[411] = "Length Required"
    resp[412] = "Precondition Failed"
    resp[413] = "Payload Too Large"
    resp[414] = "Request-URI Too Long"
    resp[415] = "Unsupported Media Type"
    resp[416] = "Requested Range Not Satisfiable"
    resp[417] = "Expectation Failed"
    resp[418] = "I'm a teapot"
    resp[421] = "Misdirected Request"
    resp[422] = "Unprocessable Entity"
    resp[423] = "Locked"
    resp[424] = "Failed Dependency"
    resp[426] = "Upgrade Required"
    resp[428] = "Precondition Required"
    resp[429] = "Too Many Requests"
    resp[431] = "Request Header Fields Too Large"
    resp[444] = "Connection Closed Without Response"
    resp[451] = "Unavailable For Legal Reasons"
    resp[499] = "Client Closed Request"

    resp[500] = "Internal Server Error"
    resp[501] = "Not Implemented"
    resp[502] = "Bad Gateway"
    resp[503] = "Service Unavailable"
    resp[504] = "Gateway Timeout"
    resp[505] = "HTTP Version Not Supported"
    resp[506] = "Variant Also Negotiates"
    resp[507] = "Insufficient Storage"
    resp[508] = "Loop Detected"
    resp[510] = "Not Extended"
    resp[511] = "Network Authentication Required"
    resp[599] = "Network Connect Timeout Error"
    resp[id.to_i]
  end
